export let SET_BALL_DIMENSION = "SET_BALL_DIMENSION";
export let SET_CURRENT_BALL_REF = "SET_CURRENT_BALL_REF";
export let SET_NEW_BALL_TRIGGER = "SET_NEW_BALL_TRIGGER";
export let ADD_BALL_REF = "ADD_BALL_REF";
export let UPDATE_BALL_REFS = "UPDATE_BALL_REFS";
export let SET_BALL_REFS_IN_PATH = "SET_BALL_REFS_IN_PATH";
export let SET_SCORE = "SET_SCORE";
export let SET_BOARD_REF = "SET_BOARD_REF";
